name: Auto Release Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin Version from Plugin File
        id: get_version
        run: |
          FILE=$(find . -name "publications-main.php" | head -n 1)
          if [ ! -f "$FILE" ]; then
            echo "❌ Could not find plugin file."
            exit 1
          fi
          VERSION=$(grep -Eo "Version:\s*[0-9.]+" "$FILE" | sed 's/Version:\s*//')
          if [ -z "$VERSION" ]; then
            echo "❌ Could not extract version from plugin file."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "✅ Detected version: $VERSION"

      - name: Create Plugin ZIP
        run: |
          cd ..
          zip -r orcid-publications.zip orcid-publications -x "*.git*" -x "*.github*" -x "vendor/*" -x "*.DS_Store"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          generate_release_notes: true
          files: ../orcid-publications.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
