name: Auto Release Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Plugin Version
        id: get_version
        run: |
          FILE=$(find . -name "publications-main.php" | head -n 1)
          if [ ! -f "$FILE" ]; then
            echo "❌ Could not find plugin file."
            exit 1
          fi
          VERSION=$(grep -Eo "Version:\s*[0-9.]+" "$FILE" | sed 's/Version:\s*//')
          if [ -z "$VERSION" ]; then
            echo "❌ Could not extract version from plugin file."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "✅ Detected version: $VERSION"

      - name: Create Plugin ZIP
        run: |
          # Create a temporary directory with correct structure
          mkdir -p temp-plugin-dir
          
          # Copy only necessary files (adjust these patterns as needed)
          cp -r *.php css/ js/ vendor/ temp-plugin-dir/
          
          # Create ZIP from the correct directory level
          cd temp-plugin-dir
          zip -r ../orcid-publications.zip .
          cd ..
          
          # Verify the ZIP structure
          unzip -l orcid-publications.zip | head -20

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}  # Remove 'v' prefix to match WordPress standards
          name: "Version ${{ env.VERSION }}"
          body: "Release of ORCID Publications plugin version ${{ env.VERSION }}"
          files: orcid-publications.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}